# Site wide configuration
title: CodeMeta
description: "A Rosetta Stone for Software Metadata"
logo: #"images/rosetta.jpg" # 120x120 px default image used for Twitter summary card
teaser: #"images/rosetta.jpg" # 400x250 px default teaser image used in image archive grid
url: #"http://codemeta.github.io"

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Carl Boettiger
  email:
  twitter: cboettig
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
