# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            CodeMeta 
tagline:          'A Rosetta Stone for Software Metadata'
description:      ''
url:              http://codemeta.github.io
baseurl:          /

author:
  name:           'Carl Boettiger'
  url:            https://twitter.com/cboettig


github:
  repo:           https://github.com/CodeMeta/codemeta
